# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./tmp:/tmp_data
      - ~/.aws/:/root/.aws:ro
    working_dir: /app
    restart: always

    environment:
      NODE_ENV: development
    ports:
      - 7100:7000
    command: npm run dev